---
  - name: collect info in new process from facts
    hosts: all
    tasks:
      - name: this is the info we have collected from host
        debug:
          msg: my name is {{ ansible_facts[ 'hostname'] }} & my OS {{ ansible_facts[ 'kernel'] }}
