---
  - name: collect info in new process from facts
    hosts: all
    tasks:
      - name: this is the info we have collected from host
        debug:
          msg: my name is {{ ansible_facts[ 'hostname'] }} and fully qualified domain name is {{ ansible_facts[ 'fqdn' ] }} main ip address is {{ ansible_facts['default_ipv4']['address'] }} size of the sda disk partition {{ ansible_facts ['devices']['sda']['partitions']['size'] }}
